format_version: 10
pipelines:
  gradle-demo-deploy:
    group: cdp
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    materials:
      upstream:
        pipeline: gradle-demo-build
        stage: gradle-demo-build
        name: upstream_pipeline
      SourceCodeRepo:
        git: https://github.com/ujjwalvns/gradle-helm.git
        shallow_clone: false
        auto_update: true
        branch: master
        name: SourceCodeRepo
    stages:
    - gradle-demo-deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  EnvironmentVariablePrefix: ''
                  SkipImagePulling: 'true'
                artifact_id: dockerhub
                pipeline: gradle-demo-build
                stage: gradle-demo-build
                job: build_project
                artifact_origin: external
                run_if: passed
            - exec:
                arguments:
                - -c
                - helm install gradle-helm ./gradle-helm/. --set image.tag=${GO_DEPENDENCY_LABEL_UPSTREAM}
                - echo 'GO_FROM_REVISION_GIT' ${GO_DEPENDENCY_LABEL_UPSTREAM}
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - echo 'GO_FROM_REVISION_GIT' ${GO_DEPENDENCY_LABEL_UPSTREAM}
                command: /bin/bash
                run_if: passed
