format_version: 10
pipelines:
  gradle-demo-deploy:
    group: cdp
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    materials:
      git:
        git: https://github.com/ujjwalvns/gradle-helm.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - gradle-demo-deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy_image:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - exec:
                arguments:
                - -c
                - ./deployment.sh
                command: /bin/sh
                run_if: passed
