format_version: 10
pipelines:
  gradle-demo-deploy:
    group: cdp
    label_template: ${UPSTREAM}
    lock_behavior: unlockWhenFinished
    display_order: 1
    materials:
      upstream:
        pipeline: gradle-build
        stage: gradle-build
        name: upstream_pipe
      SourceCodeRepo:
        git: https://github.com/ujjwalvns/gradle-helm.git
        shallow_clone: true
        auto_update: true
        branch: master
        name: SourceCodeRepo
    stages:
    - gradle-demo-deploy:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  EnvironmentVariablePrefix: ''
                  SkipImagePulling: 'true'
                artifact_id: dockerhub 
                pipeline: gradle-build
                stage: gradle-build
                job: build
                artifact_origin: external
                run_if: passed
            - exec:
                arguments:
                - -c
                - echo 'GO_FROM_REVISION_GIT' ${GO_FROM_REVISION_UPSTREAM}
                command: /bin/bash
                run_if: passed
